### PR TITLE
Refactor backend to work with front-end repo

### PR DESCRIPTION
**Pull request by chris-french**
This refactor of the meep backend code base:

- Simplifies the backend code
- Uses PostgreSQL/PostGIS as the only test/production database
- Adds a new `README.md` with install instructions (the old readme is now at `README.old.md`)

The primary goal of this PR is the first step in getting the backend to integrate with the frontend.

### CODE REVIEW

**Comment by chrisschaaf** [comment]
Minor: with pipenv now managing dependencies, can `api/app/requirements.txt` be deleted?

**Comment by chrisschaaf** [comment]
@chris-french it looks like there were some existing `postgis` and `postgres` branches already existing out there that we could merge into, but given their age some rebasing might need to be done.

**Comment by chrisschaaf** [comment]
Throwing this here as a note / maybe some readme suggestions. I ran into a few issues setting dependencies up on macos 10.15: https://stackoverflow.com/a/57014480

Haven't used postgres/gis before, that was a little unclear but worked through it. Would like to make sure my basic process was correct:
```
psql postgres
CREATE USER "postgres" WITH PASSWORD '1234';
CREATE DATABASE "meep-test" WITH OWNER "postgres";
\connect meep-test
# Installed extensions listed under 'Enabling PostGIS': https://postgis.net/install/
```

Got the `/ping` page up though, so was able to validate! +1.

**Comment by chris-french** [comment]
@chrisschaaf Awesome! There doesn't seem to be any merge conflicts with the `postgres` branch -- should we just merge this today so I can start creating PRs from this branch this week?

Sorry about the lack of clarification in the new Readme -- I think I assumed the user already created a database. When you create the database `meep-test` you'll also need to add the PostGIS extension, e.g.

```sh
psql -d meep-test -c "CREATE EXTENSION postgis;"
```

But I would recommend using [pgAdmin](https://www.pgadmin.org/) for interacting with postgresql, at least for testing and development.

**Pull request merged**
