### PR TITLE
moved BaseModel to models.py

### PR DESCRIPTION
**Pull request by t-ketchem**

### CODE REVIEW

**Review by galbwe — APPROVED** [review]
Nice. It looks like the server runs with these changes. The locations endpoints are behaving strangely, but I think they were like that before this PR. Once we have set up some unit tests, we can sort them out.

**Review by evanharmon1 — COMMENTED** [review]
I couldn't get it working on my end. But maybe I'm just getting caught between the various environments we are moving between. I think from my end I just need to know from what point to start adding tests. PR #21 is working for me with the new src folder structure. I could start adding tests from there. Or should I try to integrate this basemodel refactor first? Or is the Docker environment far enough along to shoot for getting that environment going first and then testing from there? Could use some direction lol.

**Comment by galbwe** [comment]
@evanharmon1 the dockerfile branch is at a point where it can be run for the purpose of development. I'm currently working on setting up containers for postgres and nginx, so we are probably safe merging into master and opening new issue for those because they might take some time. If you want to get tests working with the container that would be fantastic.

Let's merge this PR first though so we don't lose Tyler's commits.

**Comment by galbwe** [comment]
@t-ketchem I just noticed that there are 2 copies of dev.db, one in the project root and the other in src.

In development.py, we might also want to make the default value of ```SQLALCHEMY_DATABASE_URI``` one of the two dev.db files, whichever you decide to keep. It seems like the majority of people jumping on the project are just going to use sqlite anyways, until postgres in a docker container is up and running.

**Pull request merged**
