### PR TITLE
Login

### PR DESCRIPTION
**Pull request by galbwe**
JSON web token authentication on api endpoints for production configuration.

### CODE REVIEW

**Comment by evanharmon1** [comment]
I'll check this out now. Is there anything in particular you would like me to look at or test?

**Comment by galbwe** [comment]
@evanharmon1 Thanks. I think I only tested that authorization was added to the ```/ping``` route, and assumed it would be added to the rest of them. If you could check that it is working as intended, i.e. throws an error when someone tries to access an endpoint without authorization, for a few other routes, that would be great.

I'm also not sure how this affects the web forms yet, since at the moment they are running in the same container as the api endpoints. I'm in the process of separating them into a separate service, but in the mean time it might be good to know whether we can run them.

**Review by evanharmon1 — CHANGES_REQUESTED** [review]
Ok, got a chance to check this out more. Looks good! Eventually got things working on my machine. The tests passed. The int typecast and token expiration config change you did helped. The login works including successive logins with proper messages. At first, I couldn't get logout and status working since it was requiring authentication, but then I figured out that the authorization token needs to be in the header. I updated the Postman Team Workspace with the format for the header that I assume it should be in, but let me know if it should be different or go ahead and change it in Postman if you want. I think its the OAUTH2.0 Bearer Authentication scheme (https://swagger.io/docs/specification/authentication/bearer-authentication/).

Did you want the ping route to be restricted to logged in users? For me it works regardless. And the other routes I tried did not seem to restrict me or require an auth token so I don't think the auth worked on the other routes. So, I think the next step would be to apply the authorization method you got working for the auth/status and auth/logout routes to the other routes that need to require authorization.

**Comment by chris-french** [comment]
Since it looks like we won't be allowing users to login for an MVP, I'm closing this PR. This code is good, but I don't think it's right for the current use case. 

I think using something more simple, like [`flask-jwt`](https://pythonhosted.org/Flask-JWT/), with only one or two tokens will work for our current use case.

**Pull request closed without merging**
